{% set name = "ipyslides" %}
{% set version = "1.8.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: aa5f3faeb06aba0c937333a8e96d923b8637859b70e86802e4269458d07e5e43

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - ipywidgets
    - markdown
    - pip
    - pillow
    - python >=3.6
  run:
    - ipywidgets
    - markdown
    - pillow
    - python >=3.6

test:
  imports:
    - ipyslides
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/massgh/ipyslides
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
