{% set name = "ipyslides" %}
{% set version = "3.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: b09a18fc9dc7b7519f569a7934fd52b6388f31cec2e9613ba2d1bb81b0345cb8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - ipywidgets >=8.0.4
    - markdown
    - markdown-customblocks
    - pip
    - pillow >=9.3.0
    - python >=3.8
  run:
    - ipywidgets
    - markdown
    - markdown-customblocks
    - pillow
    - python >=3.8

test:
  imports:
    - ipyslides
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/massgh/ipyslides
  doc_url: https://massgh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
