{% set name = "ipyslides" %}
{% set version = "3.6.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: f728f3632b1f4da756b52115b4cbf307428c0dcca91300fe640a30bfb4ba2c70

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - markdown
    - markdown-customblocks
    - ipywidgets >=8.0.4
    - pillow >=9.3.0
    - anywidget ==0.7.1
    - tldraw ==2.0.2

    # Not listed but pip check complains
    - numpy

test:
  imports:
    - ipyslides
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/massgh/ipyslides
  doc_url: https://massgh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
