{% set name = "ipyslides" %}
{% set version = "5.8.993" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: 75ee21d678cfb508da772644e036a4a150089a16586f387f5cfb0d53853408e6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - markdown
    - ipywidgets >=8.0.4
    - pillow >=9.3.0
    - anywidget ==0.9.13
    # tldraw 2.2.4 is malformed and cannot be onboarded to conda
    - tldraw >=2.2.4

    # Not listed but pip check complains
    - numpy

test:
  files:
    - ipython_test.py
  commands:
    # Skip pip check because of tldraw
    # - pip check
    - ipython ipython_test.py
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/asaboor-gh/ipyslides
  doc_url: https://asaboor-gh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
