{% set name = "ipyslides" %}
{% set version = "5.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: 9c512a23f85760a9f988ae3393efb3b9fcfa3e77bac9e366ba2bc548e64cbe41

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - anywidget ==0.9.13
    # tldraw 2.2.4 is malformed and cannot be onboarded to conda
    - tldraw >=2.2.4
    - ipython >=8.7
    - markdown
    - altair
    - ipywidgets >=8.0.4
    - numpy
    - pandas
    - matplotlib-base
    - voila >=0.4.0
    - pillow >=9.3.0
    - plotly ==6.0.1
    - dashlab

test:
  files:
    - ipython_test.py
  commands:
    # Skip pip check because of tldraw
    # - pip check
    - ipython ipython_test.py
  requires:
    - pip
    - python {{ python_min }}
about:
  home: https://github.com/asaboor-gh/ipyslides
  doc_url: https://asaboor-gh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
