{% set name = "ipyslides" %}
{% set version = "4.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyslides-{{ version }}.tar.gz
  sha256: cf56e75d03011a55ed8e6c7d1bbdd4b346190a9d431b2856af256fb3201010a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    # Package seems to rely on standard library collections.Iterable, which is deprecated in 3.10
    - python >=3.8,<3.10
    - pip
  run:
    - python >=3.8,<3.10
    - markdown
    - markdown-customblocks
    - ipywidgets >=8.0.4
    - pillow >=9.3.0
    - anywidget ==0.7.1
    - tldraw ==2.0.2

    # Not listed but pip check complains
    - numpy

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/massgh/ipyslides
  doc_url: https://massgh.github.io/ipyslides/
  summary: Live rich content slides in jupyter notebook
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
